name: Validate with hassfest

on:
  push:
  pull_request: ~

jobs:
  formatting:
    name: Formatting Check
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.x"
      - run: python3 -m pip install black
      - run: black .        
        
  validate:
    name: Validate component
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v2"

        - name: HACS validation
          uses: "hacs/integration/action@master"
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CATEGORY: "integration"

        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"
