name: Pytest

on:
  push:
    branches: [tests]
  pull_request:
    branches: [tests]
  schedule:
    - cron: "0 7 1-28/7 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |

          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
      - name: Test with pytest
        run: |
          python -m pytest
